
module.exports = {
  extends: 'lighthouse:default',
  settings: {
    onlyCategories: ['performance'],
    skipAudits: [
      'uses-http2',
      'uses-long-cache-ttl',
      'uses-optimized-images',
      'uses-webp-images',
      'uses-text-compression',
      'uses-responsive-images',
      'efficient-animated-content',
      'redirects',
      'uses-rel-preconnect',
      'uses-rel-preload',
      'server-response-time',
      'network-requests',
      'network-rtt',
      'network-server-latency',
      'main-thread-tasks',
      'bootup-time',
      'mainthread-work-breakdown',
      'dom-size',
      'critical-request-chains',
      'user-timings',
      'render-blocking-resources',
      'unminified-css',
      'unminified-javascript',
      'unused-css-rules',
      'unused-javascript',
      'offscreen-images',
      'total-byte-weight',
      'third-party-summary',
      'third-party-facades',
      'largest-contentful-paint-element',
      'layout-shifts',
      'unsized-images',
      'viewport',
      'no-document-write',
      'script-treemap-data',
      'resource-summary',
      'third-party-summary',
      'legacy-javascript',
      'duplicated-javascript',
      'inspector-issues',
      'valid-source-maps',
      'preload-lcp-image',
      'csp-xss',
      'is-on-https',
      'uses-passive-event-listeners',
      'no-unload-listeners',
      'bf-cache',
      'password-inputs-can-be-pasted-into',
      'image-size-responsive',
      'image-aspect-ratio',
      'meta-description',
      'http-status-code',
      'link-text',
      'crawlable-anchors',
      'robots-txt',
      'tap-targets',
      'hreflang',
      'plugins',
      'canonical',
      'structured-data'
    ],
    emulatedFormFactor: 'desktop',
    throttling: {
      rttMs: 40,
      throughputKbps: 10240,
      cpuSlowdownMultiplier: 1,
      requestLatencyMs: 0,
      downloadThroughputKbps: 0,
      uploadThroughputKbps: 0
    },
    throttlingMethod: 'simulate',
    screenEmulation: {
      mobile: false,
      width: 1350,
      height: 940,
      deviceScaleFactor: 1,
      disabled: false
    }
  }
};
